/**
 * Leni's Shop catalog. Art lives in /public/images/generated/shop/{id}.png
 * (generated by scripts/generate-shop-items.ts); emoji is the fallback while
 * art is missing. Prices are tiered so there's always a next goal:
 * small treats ~10-15, toys ~20-35, big wacky dream items ~50-80.
 */
export interface ShopItem {
  id: string;
  name: string;
  emoji: string;
  price: number;
}

export const SHOP_ITEMS: ShopItem[] = [
  // Sweet treats (quick wins)
  { id: 'ice-cream', name: 'Ice Cream', emoji: '🍦', price: 10 },
  { id: 'lollipop', name: 'Rainbow Lollipop', emoji: '🍭', price: 10 },
  { id: 'donut', name: 'Sprinkle Donut', emoji: '🍩', price: 12 },
  { id: 'cotton-candy', name: 'Cotton Candy', emoji: '🍬', price: 12 },
  { id: 'cupcake', name: 'Magic Cupcake', emoji: '🧁', price: 15 },

  // Toys
  { id: 'teddy', name: 'Teddy Bear', emoji: '🧸', price: 20 },
  { id: 'balloon-unicorn', name: 'Unicorn Balloon', emoji: '🦄', price: 20 },
  { id: 'toy-dino', name: 'Toy Dinosaur', emoji: '🦕', price: 25 },
  { id: 'race-car', name: 'Race Car', emoji: '🏎️', price: 25 },
  { id: 'robot', name: 'Silly Robot', emoji: '🤖', price: 30 },
  { id: 'skateboard', name: 'Skateboard', emoji: '🛹', price: 30 },
  { id: 'bubble-machine', name: 'Bubble Machine', emoji: '🫧', price: 35 },
  { id: 'silly-sunglasses', name: 'Silly Sunglasses', emoji: '😎', price: 35 },

  // Wacky wonders
  { id: 'magic-wand', name: 'Magic Wand', emoji: '🪄', price: 40 },
  { id: 'crown', name: 'Sparkly Crown', emoji: '👑', price: 40 },
  { id: 'disco-ball', name: 'Disco Ball', emoji: '🪩', price: 45 },
  { id: 'fairy-wings', name: 'Fairy Wings', emoji: '🧚', price: 45 },
  { id: 'goldfish', name: 'Pet Goldfish', emoji: '🐠', price: 50 },
  { id: 'treasure-chest', name: 'Treasure Chest', emoji: '🪙', price: 55 },
  { id: 'dragon-egg', name: 'Dragon Egg', emoji: '🥚', price: 60 },
  { id: 'jetpack', name: 'Jetpack', emoji: '🚀', price: 70 },
  { id: 'rainbow-slide', name: 'Rainbow Slide', emoji: '🌈', price: 75 },
  { id: 'bouncy-castle', name: 'Bouncy Castle', emoji: '🏰', price: 80 },
  { id: 'pirate-ship', name: 'Pirate Ship', emoji: '⛵', price: 80 },
];

/** Build-time prompts for the wacky art generator. */
export const SHOP_ART_PROMPTS: Record<string, string> = {
  'ice-cream': 'a triple-scoop rainbow ice cream cone with a smiley face, melting playfully',
  lollipop: 'a giant swirly rainbow lollipop with sparkles',
  donut: 'a goofy donut with rainbow sprinkles and one bite taken out, winking',
  'cotton-candy': 'a fluffy pink and blue cotton candy cloud with a happy face',
  cupcake: 'a magical cupcake with glowing star sprinkles and a tiny crown on top',
  teddy: 'a cuddly patchwork teddy bear waving hello',
  'balloon-unicorn': 'a unicorn-shaped rainbow balloon floating with curly string',
  'toy-dino': 'a chunky friendly toy dinosaur with big cartoon eyes, wearing sneakers',
  'race-car': 'a zany red race car with googly eyes and a big smile',
  robot: 'a silly friendly robot with springy arms juggling stars',
  skateboard: 'a cool skateboard with flame and star stickers',
  'bubble-machine': 'a whimsical bubble machine blowing rainbow bubbles everywhere',
  'silly-sunglasses': 'giant star-shaped sunglasses, sparkling, super silly',
  'magic-wand': 'a glittering magic wand shooting tiny stars and hearts',
  crown: 'a sparkly golden crown with colorful jewels, slightly tilted',
  'disco-ball': 'a shiny disco ball with rainbow light beams and a smiley face',
  'fairy-wings': 'iridescent sparkly fairy wings, glowing softly',
  goldfish: 'a happy goldfish doing a flip in a round fishbowl',
  'treasure-chest': 'an overflowing treasure chest of gold coins and rainbow gems',
  'dragon-egg': 'a mysterious glowing dragon egg with sparkles, slightly cracked with a tiny eye peeking out',
  jetpack: 'a cartoon jetpack with rainbow flames and silly warning stickers',
  'rainbow-slide': 'a giant playground slide shaped like a rainbow ending in a cloud',
  'bouncy-castle': 'a wacky colorful bouncy castle with balloons and flags',
  'pirate-ship': 'a goofy little pirate ship with a skull-and-crossbones flag wearing a party hat',
};
