import type { ContentPack, ContentWord, GraphemeUnit } from '../types';

const unit = (text: string, phonemeId = text): GraphemeUnit => ({ text, phonemeId });
const earlyPractice = ['initial-sound', 'letter-match'] as const;
const earlyBlend = ['blend-to-picture', 'picture-to-build'] as const;

const word = (
  text: string,
  units: GraphemeUnit[],
  activities: ContentWord['activities'],
): ContentWord => ({
  id: `alphabet-adventure:${text}`,
  text,
  units,
  picturePath: `/images/generated/items/${text}.png`,
  audioPath: `/audio/words/${text}.mp3`,
  activities,
});

const initial = (text: string, first: string) => word(text, [unit(first)], [...earlyPractice]);
const blend = (text: string, letters: string[], includeInitial = true) => word(
  text,
  letters.map((letter) => unit(letter, letter === 'c' ? 'c' : letter)),
  includeInitial ? [...earlyPractice, ...earlyBlend] : [...earlyBlend],
);

/**
 * Default-on but removable. It expands the early worlds without replacing a
 * single mechanic. Letter Intro rotates through all 26 letters; initial-sound
 * games use the scientifically clean start-sound groups; x is taught in the
 * decodable final position in "fox" rather than with misleading xylophone.
 */
export const ALPHABET_ADVENTURE_PACK: ContentPack = {
  id: 'alphabet-adventure',
  name: 'Alphabet Adventure',
  description: 'Rotates through the whole alphabet and adds many new early-game pictures and words.',
  focus: 'all 26 letters, with x in fox',
  optional: true,
  requiredPackIds: [],
  prerequisitePhonemes: ['s', 'a', 't', 'p', 'i', 'n', 'e', 'l'],
  introducedPhonemes: ['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'm', 'o', 'q', 'r', 'u', 'v', 'w', 'x', 'y', 'z'],
  words: [
    initial('ball', 'b'),
    initial('bird', 'b'),
    initial('bus', 'b'),
    initial('banana', 'b'),
    blend('cap', ['c', 'a', 'p']),
    initial('car', 'c'),
    blend('can', ['c', 'a', 'n']),
    initial('dinosaur', 'd'),
    blend('dot', ['d', 'o', 't']),
    blend('den', ['d', 'e', 'n']),
    initial('fish', 'f'),
    blend('fan', ['f', 'a', 'n']),
    blend('fox', ['f', 'o', 'x']),
    blend('fog', ['f', 'o', 'g']),
    initial('goat', 'g'),
    blend('hen', ['h', 'e', 'n']),
    blend('hog', ['h', 'o', 'g']),
    blend('hut', ['h', 'u', 't']),
    blend('jet', ['j', 'e', 't']),
    blend('jug', ['j', 'u', 'g']),
    blend('jog', ['j', 'o', 'g']),
    initial('kite', 'k'),
    initial('moon', 'm'),
    initial('mouse', 'm'),
    initial('milk', 'm'),
    initial('monkey', 'm'),
    blend('map', ['m', 'a', 'p']),
    blend('man', ['m', 'a', 'n']),
    blend('mug', ['m', 'u', 'g']),
    initial('octopus', 'o'),
    initial('queen', 'q'),
    initial('rabbit', 'r'),
    initial('rain', 'r'),
    blend('rat', ['r', 'a', 't']),
    blend('rug', ['r', 'u', 'g']),
    blend('run', ['r', 'u', 'n']),
    initial('umbrella', 'u'),
    blend('van', ['v', 'a', 'n']),
    initial('watermelon', 'w'),
    blend('wet', ['w', 'e', 't']),
    blend('win', ['w', 'i', 'n']),
    initial('yo-yo', 'y'),
    initial('zebra', 'z'),

    // Familiar concrete CVCs become available for World 3 only while this
    // pack is enabled. Duplicating their media records keeps core removable.
    blend('cat', ['c', 'a', 't']),
    blend('hat', ['h', 'a', 't']),
    blend('bat', ['b', 'a', 't']),
    blend('mat', ['m', 'a', 't']),
    blend('bin', ['b', 'i', 'n']),
    blend('dog', ['d', 'o', 'g']),
    blend('log', ['l', 'o', 'g'], false),
    blend('hot', ['h', 'o', 't']),
    blend('pot', ['p', 'o', 't'], false),
    blend('cup', ['c', 'u', 'p']),
    blend('pup', ['p', 'u', 'p'], false),
    blend('bed', ['b', 'e', 'd']),
    blend('red', ['r', 'e', 'd']),
    blend('cot', ['c', 'o', 't']),
    blend('pug', ['p', 'u', 'g'], false),
  ],
  letterExamples: [
    { id: 'alphabet:letter-b', letter: 'b', phonemeId: 'b', word: 'ball', soundPosition: 'start' },
    { id: 'alphabet:letter-c', letter: 'c', phonemeId: 'c', word: 'cat', soundPosition: 'start' },
    { id: 'alphabet:letter-d', letter: 'd', phonemeId: 'd', word: 'dog', soundPosition: 'start' },
    { id: 'alphabet:letter-f', letter: 'f', phonemeId: 'f', word: 'fish', soundPosition: 'start' },
    { id: 'alphabet:letter-g', letter: 'g', phonemeId: 'g', word: 'goat', soundPosition: 'start' },
    { id: 'alphabet:letter-h', letter: 'h', phonemeId: 'h', word: 'hat', soundPosition: 'start' },
    { id: 'alphabet:letter-j', letter: 'j', phonemeId: 'j', word: 'jet', soundPosition: 'start' },
    { id: 'alphabet:letter-k', letter: 'k', phonemeId: 'k', word: 'kite', soundPosition: 'start' },
    { id: 'alphabet:letter-m', letter: 'm', phonemeId: 'm', word: 'moon', soundPosition: 'start' },
    { id: 'alphabet:letter-o', letter: 'o', phonemeId: 'o', word: 'octopus', soundPosition: 'start' },
    { id: 'alphabet:letter-q', letter: 'q', phonemeId: 'q', word: 'queen', soundPosition: 'start' },
    { id: 'alphabet:letter-r', letter: 'r', phonemeId: 'r', word: 'rabbit', soundPosition: 'start' },
    { id: 'alphabet:letter-u', letter: 'u', phonemeId: 'u', word: 'umbrella', soundPosition: 'start' },
    { id: 'alphabet:letter-v', letter: 'v', phonemeId: 'v', word: 'van', soundPosition: 'start' },
    { id: 'alphabet:letter-w', letter: 'w', phonemeId: 'w', word: 'watermelon', soundPosition: 'start' },
    { id: 'alphabet:letter-x', letter: 'x', phonemeId: 'x', word: 'fox', soundPosition: 'end' },
    { id: 'alphabet:letter-y', letter: 'y', phonemeId: 'y', word: 'yo-yo', soundPosition: 'start' },
    { id: 'alphabet:letter-z', letter: 'z', phonemeId: 'z', word: 'zebra', soundPosition: 'start' },
  ],
  initialSoundGroups: [
    { id: 'alphabet:b', letter: 'b', phonemeId: 'b', wordIds: ['alphabet-adventure:ball', 'alphabet-adventure:bird', 'alphabet-adventure:bus', 'alphabet-adventure:banana'] },
    { id: 'alphabet:c', letter: 'c', phonemeId: 'c', wordIds: ['alphabet-adventure:cat', 'alphabet-adventure:cap', 'alphabet-adventure:car', 'alphabet-adventure:can'] },
    { id: 'alphabet:d', letter: 'd', phonemeId: 'd', wordIds: ['alphabet-adventure:dog', 'alphabet-adventure:dinosaur', 'alphabet-adventure:dot', 'alphabet-adventure:den'] },
    { id: 'alphabet:f', letter: 'f', phonemeId: 'f', wordIds: ['alphabet-adventure:fish', 'alphabet-adventure:fan', 'alphabet-adventure:fox', 'alphabet-adventure:fog'] },
    { id: 'alphabet:g', letter: 'g', phonemeId: 'g', wordIds: ['alphabet-adventure:goat'] },
    { id: 'alphabet:h', letter: 'h', phonemeId: 'h', wordIds: ['alphabet-adventure:hat', 'alphabet-adventure:hen', 'alphabet-adventure:hog', 'alphabet-adventure:hut'] },
    { id: 'alphabet:j', letter: 'j', phonemeId: 'j', wordIds: ['alphabet-adventure:jet', 'alphabet-adventure:jug', 'alphabet-adventure:jog'] },
    { id: 'alphabet:k', letter: 'k', phonemeId: 'k', wordIds: ['alphabet-adventure:kite'] },
    { id: 'alphabet:m', letter: 'm', phonemeId: 'm', wordIds: ['alphabet-adventure:moon', 'alphabet-adventure:mouse', 'alphabet-adventure:milk', 'alphabet-adventure:monkey', 'alphabet-adventure:map'] },
    { id: 'alphabet:o', letter: 'o', phonemeId: 'o', wordIds: ['alphabet-adventure:octopus'] },
    { id: 'alphabet:q', letter: 'q', phonemeId: 'q', wordIds: ['alphabet-adventure:queen'] },
    { id: 'alphabet:r', letter: 'r', phonemeId: 'r', wordIds: ['alphabet-adventure:rabbit', 'alphabet-adventure:rain', 'alphabet-adventure:rat', 'alphabet-adventure:rug', 'alphabet-adventure:run'] },
    { id: 'alphabet:u', letter: 'u', phonemeId: 'u', wordIds: ['alphabet-adventure:umbrella'] },
    { id: 'alphabet:v', letter: 'v', phonemeId: 'v', wordIds: ['alphabet-adventure:van'] },
    { id: 'alphabet:w', letter: 'w', phonemeId: 'w', wordIds: ['alphabet-adventure:watermelon', 'alphabet-adventure:wet', 'alphabet-adventure:win'] },
    { id: 'alphabet:y', letter: 'y', phonemeId: 'y', wordIds: ['alphabet-adventure:yo-yo'] },
    { id: 'alphabet:z', letter: 'z', phonemeId: 'z', wordIds: ['alphabet-adventure:zebra'] },
  ],
  rhymeFamilies: [
    { id: 'alphabet:rhyme-up', words: ['cup', 'pup'] },
    { id: 'alphabet:rhyme-an', words: ['pan', 'fan', 'can', 'man'] },
    { id: 'alphabet:rhyme-ed', words: ['bed', 'red', 'fed'] },
    { id: 'alphabet:rhyme-un', words: ['sun', 'run'] },
    { id: 'alphabet:rhyme-ot', words: ['pot', 'hot', 'cot', 'dot'] },
    { id: 'alphabet:rhyme-et', words: ['net', 'pet', 'wet', 'jet'] },
    { id: 'alphabet:rhyme-ar', words: ['car', 'star'] },
  ],
  syllableWords: [
    { id: 'alphabet:syllable-ball', word: 'ball', syllables: 1, spokenSyllables: 'ball' },
    { id: 'alphabet:syllable-fish', word: 'fish', syllables: 1, spokenSyllables: 'fish' },
    { id: 'alphabet:syllable-moon', word: 'moon', syllables: 1, spokenSyllables: 'moon' },
    { id: 'alphabet:syllable-tiger', word: 'tiger', syllables: 2, spokenSyllables: 'ti... ger' },
    { id: 'alphabet:syllable-turtle', word: 'turtle', syllables: 2, spokenSyllables: 'tur... tle' },
    { id: 'alphabet:syllable-penguin', word: 'penguin', syllables: 2, spokenSyllables: 'pen... guin' },
    { id: 'alphabet:syllable-lion', word: 'lion', syllables: 2, spokenSyllables: 'li... on' },
    { id: 'alphabet:syllable-lemon', word: 'lemon', syllables: 2, spokenSyllables: 'lem... on' },
    { id: 'alphabet:syllable-insect', word: 'insect', syllables: 2, spokenSyllables: 'in... sect' },
    { id: 'alphabet:syllable-igloo', word: 'igloo', syllables: 2, spokenSyllables: 'ig... loo' },
    { id: 'alphabet:syllable-zebra', word: 'zebra', syllables: 2, spokenSyllables: 'ze... bra' },
    { id: 'alphabet:syllable-yo-yo', word: 'yo-yo', syllables: 2, spokenSyllables: 'yo... yo' },
    { id: 'alphabet:syllable-octopus', word: 'octopus', syllables: 3, spokenSyllables: 'oc... to... pus' },
    { id: 'alphabet:syllable-umbrella', word: 'umbrella', syllables: 3, spokenSyllables: 'um... brel... la' },
  ],
  wordChains: [],
  stories: [],
  postcards: [],
};
