import type { ContentPack, ContentWord, GraphemeUnit } from '../types';

const unit = (text: string, phonemeId = text): GraphemeUnit => ({ text, phonemeId });

const word = (
  text: string,
  units: GraphemeUnit[],
  activities: ContentWord['activities'],
): ContentWord => ({
  id: `core:${text}`,
  text,
  units,
  picturePath: `/images/generated/items/${text}.png`,
  audioPath: `/audio/words/${text}.mp3`,
  activities,
});

const blendBuild = ['blend-to-picture', 'picture-to-build'] as const;

export const CORE_PACK: ContentPack = {
  id: 'core',
  name: 'SATPIN + Eleni',
  description: 'The original foundation words and sounds.',
  focus: 's, a, t, p, i, n, e, l',
  optional: false,
  requiredPackIds: [],
  prerequisitePhonemes: [],
  introducedPhonemes: ['s', 'a', 't', 'p', 'i', 'n', 'e', 'l'],
  words: [
    word('ant', [unit('a'), unit('n'), unit('t')], [...blendBuild]),
    word('sat', [unit('s'), unit('a'), unit('t')], []),
    word('sit', [unit('s'), unit('i'), unit('t')], []),
    word('tap', [unit('t'), unit('a'), unit('p')], []),
    word('pen', [unit('p'), unit('e'), unit('n')], [...blendBuild, 'word-chain']),
    word('lip', [unit('l'), unit('i'), unit('p')], [...blendBuild]),
    word('net', [unit('n'), unit('e'), unit('t')], [...blendBuild]),
    word('pin', [unit('p'), unit('i'), unit('n')], [...blendBuild, 'word-chain']),
    word('nap', [unit('n'), unit('a'), unit('p')], []),
    word('sip', [unit('s'), unit('i'), unit('p')], []),
    word('tin', [unit('t'), unit('i'), unit('n')], []),
    word('ten', [unit('t'), unit('e'), unit('n')], [...blendBuild]),
    word('pan', [unit('p'), unit('a'), unit('n')], [...blendBuild]),
    word('pit', [unit('p'), unit('i'), unit('t')], []),
    word('pet', [unit('p'), unit('e'), unit('t')], []),
    word('cat', [unit('c', 'c'), unit('a'), unit('t')], ['word-chain']),
    word('hat', [unit('h'), unit('a'), unit('t')], ['word-chain']),
    word('bin', [unit('b'), unit('i'), unit('n')], []),
    word('hot', [unit('h'), unit('o'), unit('t')], ['word-chain']),
    word('pot', [unit('p'), unit('o'), unit('t')], ['word-chain']),
    word('bat', [unit('b'), unit('a'), unit('t')], ['word-chain']),
    word('mat', [unit('m'), unit('a'), unit('t')], ['word-chain']),
    word('dog', [unit('d'), unit('o'), unit('g')], ['word-chain']),
    word('log', [unit('l'), unit('o'), unit('g')], ['word-chain']),
    word('cup', [unit('c', 'c'), unit('u'), unit('p')], ['word-chain']),
    word('pup', [unit('p'), unit('u'), unit('p')], ['word-chain']),
    ...[
      ['sun', 's'], ['sock', 's'], ['star', 's'], ['snake', 's'],
      ['apple', 'a'], ['tiger', 't'], ['tent', 't'], ['pig', 'p'],
      ['penguin', 'p'], ['igloo', 'i'], ['insect', 'i'], ['nest', 'n'],
      ['nut', 'n'], ['egg', 'e'], ['elephant', 'e'], ['lion', 'l'],
      ['lemon', 'l'],
    ].map(([text, first]) => word(text, [unit(first)], ['initial-sound', 'letter-match'])),
  ],
  letterExamples: [
    { id: 'core:letter-s', letter: 's', phonemeId: 's', word: 'sun', soundPosition: 'start' },
    { id: 'core:letter-a', letter: 'a', phonemeId: 'a', word: 'apple', soundPosition: 'start' },
    { id: 'core:letter-t', letter: 't', phonemeId: 't', word: 'tiger', soundPosition: 'start' },
    { id: 'core:letter-p', letter: 'p', phonemeId: 'p', word: 'pig', soundPosition: 'start' },
    { id: 'core:letter-i', letter: 'i', phonemeId: 'i', word: 'igloo', soundPosition: 'start' },
    { id: 'core:letter-n', letter: 'n', phonemeId: 'n', word: 'nest', soundPosition: 'start' },
    { id: 'core:letter-e', letter: 'e', phonemeId: 'e', word: 'egg', soundPosition: 'start' },
    { id: 'core:letter-l', letter: 'l', phonemeId: 'l', word: 'lion', soundPosition: 'start' },
  ],
  initialSoundGroups: [
    { id: 'core:s', letter: 's', phonemeId: 's', wordIds: ['core:sun', 'core:sock', 'core:star', 'core:snake'] },
    { id: 'core:a', letter: 'a', phonemeId: 'a', wordIds: ['core:ant', 'core:apple'] },
    { id: 'core:t', letter: 't', phonemeId: 't', wordIds: ['core:tiger', 'core:tent'] },
    { id: 'core:p', letter: 'p', phonemeId: 'p', wordIds: ['core:pig', 'core:penguin', 'core:pen'] },
    { id: 'core:i', letter: 'i', phonemeId: 'i', wordIds: ['core:igloo', 'core:insect'] },
    { id: 'core:n', letter: 'n', phonemeId: 'n', wordIds: ['core:nest', 'core:nut', 'core:net'] },
    { id: 'core:e', letter: 'e', phonemeId: 'e', wordIds: ['core:egg', 'core:elephant'] },
    { id: 'core:l', letter: 'l', phonemeId: 'l', wordIds: ['core:lion', 'core:lemon', 'core:lip'] },
  ],
  rhymeFamilies: [
    { id: 'core:rhyme-at', words: ['cat', 'hat', 'bat'] },
    { id: 'core:rhyme-ug', words: ['bug', 'mug', 'rug'] },
    { id: 'core:rhyme-og', words: ['log', 'dog'] },
    { id: 'core:rhyme-en', words: ['hen', 'ten'] },
  ],
  syllableWords: [
    { id: 'core:syllable-cat', word: 'cat', syllables: 1, spokenSyllables: 'cat' },
    { id: 'core:syllable-dog', word: 'dog', syllables: 1, spokenSyllables: 'dog' },
    { id: 'core:syllable-sun', word: 'sun', syllables: 1, spokenSyllables: 'sun' },
    { id: 'core:syllable-apple', word: 'apple', syllables: 2, spokenSyllables: 'ap... pull' },
    { id: 'core:syllable-monkey', word: 'monkey', syllables: 2, spokenSyllables: 'mon... key' },
    { id: 'core:syllable-rabbit', word: 'rabbit', syllables: 2, spokenSyllables: 'rab... bit' },
    { id: 'core:syllable-banana', word: 'banana', syllables: 3, spokenSyllables: 'ba... na... na' },
    { id: 'core:syllable-elephant', word: 'elephant', syllables: 3, spokenSyllables: 'el... eh... fant' },
    { id: 'core:syllable-tomato', word: 'tomato', syllables: 3, spokenSyllables: 'to... may... to' },
    { id: 'core:syllable-butterfly', word: 'butterfly', syllables: 3, spokenSyllables: 'but... ter... fly' },
    { id: 'core:syllable-dinosaur', word: 'dinosaur', syllables: 3, spokenSyllables: 'dy... no... soar' },
    { id: 'core:syllable-watermelon', word: 'watermelon', syllables: 4, spokenSyllables: 'wa... ter... mel... on' },
  ],
  wordChains: [
    { id: 'core:pin-pen', fromWordId: 'core:pin', toWordId: 'core:pen', changedUnitIndex: 1, distractorUnits: [unit('a')] },
    { id: 'core:pen-pin', fromWordId: 'core:pen', toWordId: 'core:pin', changedUnitIndex: 1, distractorUnits: [unit('a')] },
    { id: 'core:pen-pan', fromWordId: 'core:pen', toWordId: 'core:pan', changedUnitIndex: 1, distractorUnits: [unit('i')] },
    { id: 'core:pan-pen', fromWordId: 'core:pan', toWordId: 'core:pen', changedUnitIndex: 1, distractorUnits: [unit('i')] },
    { id: 'core:ten-pen', fromWordId: 'core:ten', toWordId: 'core:pen', changedUnitIndex: 0, distractorUnits: [unit('n')] },
    { id: 'core:pen-ten', fromWordId: 'core:pen', toWordId: 'core:ten', changedUnitIndex: 0, distractorUnits: [unit('n')] },
    { id: 'core:cat-hat', fromWordId: 'core:cat', toWordId: 'core:hat', changedUnitIndex: 0, distractorUnits: [unit('s')] },
    { id: 'core:dog-log', fromWordId: 'core:dog', toWordId: 'core:log', changedUnitIndex: 0, distractorUnits: [unit('n')] },
  ],
  stories: [
    { id: 'story:bed', text: 'Sam sat on the bed.', pictureWord: 'bed', question: 'What did Sam sit on?', correct: 'bed', options: ['bed', 'cat', 'hat'], cue: 'self-read-sentence' },
    { id: 'story:big-cat', text: 'The cat is big.', pictureWord: 'cat', question: 'What is big?', correct: 'cat', options: ['cat', 'dog', 'bug'], cue: 'self-read-sentence' },
    { id: 'story:bug-log', text: 'The bug is on the log.', pictureWord: 'bug', question: 'Where is the bug?', correct: 'log', options: ['log', 'cup', 'hat'], cue: 'self-read-sentence' },
    { id: 'story:red-hat', text: 'He got the red hat.', pictureWord: 'hat', question: 'What did he get?', correct: 'hat', options: ['hat', 'cup', 'net'], cue: 'self-read-sentence' },
    { id: 'story:fish-net', text: 'The fish is in the net.', pictureWord: 'net', question: 'Where is the fish?', correct: 'net', options: ['net', 'bed', 'cup'], cue: 'self-read-sentence' },
    { id: 'story:see-ship', text: 'She is on the ship.', pictureWord: 'ship', question: 'Where is she?', correct: 'ship', options: ['ship', 'cat', 'dog'], cue: 'self-read-sentence' },
    { id: 'story:pet-dog', text: 'He got the pet dog.', pictureWord: 'dog', question: 'What pet did he get?', correct: 'dog', options: ['dog', 'cat', 'fish'], cue: 'self-read-sentence' },
  ],
  postcards: [
    { id: 'postcard:fish', template: 'The ___ is big.', spoken: 'The blank is big.', correct: 'fish', options: ['fish', 'cat', 'log'], cue: 'picture-only' },
    { id: 'postcard:hat', template: 'The ___ is big.', spoken: 'The blank is big.', correct: 'hat', options: ['hat', 'net', 'cup'], cue: 'picture-only' },
    { id: 'postcard:log', template: 'She sat on the ___.', spoken: 'She sat on the blank.', correct: 'log', options: ['log', 'mug', 'bat'], cue: 'picture-only' },
    { id: 'postcard:dog', template: 'He got the pet ___.', spoken: 'He got the pet blank.', correct: 'dog', options: ['hen', 'dog', 'cat'], cue: 'picture-only' },
    { id: 'postcard:cat', template: 'The ___ is on the mat.', spoken: 'The blank is on the mat.', correct: 'cat', options: ['bat', 'cat', 'hat'], cue: 'picture-only' },
  ],
};
