/** Regenerates src/lib/itemArt.ts from the files in public/images/generated/items/. */
import * as fs from 'fs';
import * as path from 'path';

const ITEMS_DIR = path.join(process.cwd(), 'public', 'images', 'generated', 'items');
const OUT = path.join(process.cwd(), 'src', 'lib', 'itemArt.ts');

const words = fs.readdirSync(ITEMS_DIR)
  .filter(f => f.endsWith('.png'))
  .map(f => f.replace(/\.png$/, ''))
  .sort();

const body = `/**
 * Words that have generated PNG art in /public/images/generated/items/.
 * AUTO-GENERATED by scripts/update-item-art-manifest.ts — do not edit by hand.
 * WordCard renders PNG art for these words and falls back to emoji otherwise.
 */
export const ITEM_ART = new Set<string>([
${words.map(w => `  '${w}',`).join('\n')}
]);
`;

fs.writeFileSync(OUT, body);
console.log(`itemArt.ts updated: ${words.length} words with art`);
